<?php

namespace AppBundle\Repository;

/**
 * WorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkRepository extends \Doctrine\ORM\EntityRepository
{

	public function numberOfWorks() {
		$works = $this->findAll();
		return count($works);
	}

	public function findAllApprovedByNumber() {
		$aQuery = $this->getEntityManager()->createQuery('select w from AppBundle:Work w where w.state = :aState order by w.number asc');
		$aQuery->setParameter(':aState', 'APPROVED');
		return $aQuery->getResult();
	}
}
